name: Test and Validate Chart 

on:
  workflow_call:
    inputs:
      runson:
        description: "Identifier of Github-hosted instance to set as runs-on for jobs"
        default: "ubuntu-18.04"
        required: false
        type: string
      chart_name:
        description: "Name of Helm Chart"
        required: true
        type: string
      chart_path:
        description: 'Path of the Helm chart'
        required: true
        type: string
      validate_namespace:
        description: "The namespace where the check command will run"
        default: "default"
        required: false
        type: string
      

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  helm-lint-validate:
    name: Lint and Validate Chart
    runs-on: ${{ inputs.runson }}

    steps:
      - uses: actions/checkout@v2

      - name: Helm lint
        run: helm lint ${{ inputs.chart_path }}
      
      - name: Helm validate
        run: |
          helm template --is-upgrade --validate --release-name "${{ inputs.chart_name }}" -f ${{ inputs.chart_path }}/values.yaml ./${{ inputs.chart_path }} --namespace ${{ inputs.validate_namespace }}
